### PR TITLE
Improvement/use shared logrotate role

### PR DESCRIPTION
**Pull request by dav3r**

### CODE REVIEW

**Comment by jsf9k** [comment]
I think it may be OK to leave the system-wide and rsyslog-specific logrotate configuration in here.  I'm not sure though.  Are you thinking of splitting that out into a separate role or repeating it in your two roles that depend on logrotate?  Or does it not need to be repeated in the non-CyHy role?

**Comment by dav3r** [comment]
The rsyslog logrotate config stuff was moved to the [new shared logrotate role](https://github.com/dhs-ncats/ansible-role-logrotate/blob/develop/tasks/main.yml#L35), which now gets run as a dependency to this cyhy-logrotate role, so I removed it here.  Or am I misunderstanding what you are asking?

**Comment by jsf9k** [comment]
No, you are correct.  I had confused myself and thought I was looking at the non-CyHy role.  I am an idiot.  *IGNORE ME!*

**Review by jsf9k — APPROVED** [review]
This is the strongest of work, @dav3r!

**Comment by dav3r** [comment]
Haha, I have already confused myself several times in the past 24 hours about which logrotate role I was working in, so believe me, I understand.

**Pull request merged**
